const $=id=>document.getElementById(id),canvas=$('arena'),ctx=canvas.getContext('2d');
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const types=['swing','projectile','charge'];
let player,targets,shots,effects,pulses,keys=new Set(),running=false,paused=false,won=false,time=0,last=0,nextPulse=5,contacts=0,dodges=0,actionDown=null,pending=null,second=false,cooldown=0,dash=0,dashReady=0,actionPointer=null;
const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function say(s){$('action').textContent=s}
function reset(){player={x:450,y:480,angle:-Math.PI/2};targets=[{x:230,y:300,type:'swing',title:'I · SWING',done:false},{x:650,y:170,type:'projectile',title:'II · PROJECTILE',done:false},{x:690,y:450,type:'charge',title:'III · CHARGE',done:false}];shots=[];effects=[];pulses=[];time=0;nextPulse=5;contacts=0;dodges=0;cooldown=0;dash=0;dashReady=0;won=false;clearInput();update();}
function clearInput(){keys.clear();actionDown=null;pending=null;second=false;actionPointer=null;document.querySelectorAll('.held').forEach(b=>b.classList.remove('held'));$('charge').value=0;$('charge-label').textContent='Hold to gather energy'}
function update(){const n=targets.filter(t=>t.done).length;$('score').textContent=n+' / 3';$('contacts').textContent=`Pulse contacts: ${contacts} · Dodges: ${dodges}`;for(const t of targets){const li=$('goal-'+t.type);li.classList.toggle('done',t.done);li.querySelector('.result').textContent=t.done?'✓':'○';li.querySelector('.result').setAttribute('aria-label',t.done?'Restored':'Incomplete')}if(n===3&&!won){won=true;running=false;clearInput();overlay('Harmony, for a moment.','Three seals restored. You’ve tried the proposal’s three attack timings. Replay to explore how the pauses between inputs change the feel.','Return to the court','Study complete');$('state-label').textContent='Court restored';enableControls(false)}}
function enableControls(on){document.querySelectorAll('.controls button').forEach(b=>b.disabled=!on);$('pause').disabled=!on&&!paused}
function overlay(title,copy,button,kicker){$('overlay-title').textContent=title;$('overlay-copy').textContent=copy;$('start').textContent=button;$('overlay-kicker').textContent=kicker;$('overlay-note').textContent=won?`${dodges} dodges · ${contacts} pulse contacts`:'WASD / arrows · Space for action · Shift to dodge';$('overlay').hidden=false}
function start(){const resuming=paused;if(!paused)reset();running=true;paused=false;$('overlay').hidden=true;$('pause').textContent='Pause';$('state-label').textContent='Training in progress';enableControls(true);canvas.focus({preventScroll:true});say(resuming?'Continue at your own pace.':'Move toward seal I, then tap once.')}
function pause(){if(!running)return;running=false;paused=true;clearInput();overlay('Take a breath.','The court is paused. Your position and restored seals are waiting.','Continue the study','Paused');$('pause').textContent='Resume';$('state-label').textContent='Paused';enableControls(false);$('start').focus({preventScroll:true})}
function nearest(){return targets.filter(t=>!t.done).sort((a,b)=>distance(a,player)-distance(b,player))[0]}
function begin(){if(!running||actionDown!==null)return;second=pending!==null&&time<=pending;if(second)pending=null;actionDown=time}
function end(){if(!running||actionDown===null)return;const held=time-actionDown;actionDown=null;if(held>=.65){pending=null;second=false;attack('charge')}else if(second){second=false;attack('projectile')}else pending=time+.26;$('charge').value=0;$('charge-label').textContent='Hold to gather energy'}
function hit(target,type){if(target.done)return;if(target.type!==type){say(`Seal ${types.indexOf(target.type)+1} needs a ${target.type==='charge'?'charged strike':target.type}.`);effects.push({kind:'reject',x:target.x,y:target.y,life:.5,max:.5});return}target.done=true;effects.push({kind:'restore',x:target.x,y:target.y,life:1,max:1});say(`${target.title.split(' · ')[0]} restored. ${targets.filter(t=>!t.done).length} seals remain.`);update()}
function attack(type){if(cooldown>0){say('Let the previous action settle, then try again.');return}const t=nearest();if(!t)return;player.angle=Math.atan2(t.y-player.y,t.x-player.x);cooldown=type==='charge'?.65:.28;effects.push({kind:type,x:player.x,y:player.y,angle:player.angle,life:.4,max:.4});say(type==='swing'?'Single tap → swing.':type==='projectile'?'Double tap → projectile.':'Hold + release → charged strike.');if(type==='projectile'){shots.push({x:player.x,y:player.y,vx:Math.cos(player.angle)*600,vy:Math.sin(player.angle)*600,life:2});return}const reach=type==='charge'?145:115;if(distance(player,t)<=reach)hit(t,type);else say((type==='swing'?'Swing':'Charged strike')+' — move closer to the nearest seal.')}
function dodge(){if(!running||dashReady>0)return;dash=.24;dashReady=1.1;dodges++;effects.push({kind:'dodge',x:player.x,y:player.y,life:.45,max:.45});say('Dodge — briefly protected from the pulse.');update()}
function step(dt){time+=dt;cooldown=Math.max(0,cooldown-dt);dashReady=Math.max(0,dashReady-dt);dash=Math.max(0,dash-dt);let dx=Number(keys.has('right'))-Number(keys.has('left')),dy=Number(keys.has('down'))-Number(keys.has('up'));const len=Math.hypot(dx,dy);if(len){dx/=len;dy/=len;player.angle=Math.atan2(dy,dx)}else if(dash>0){dx=Math.cos(player.angle);dy=Math.sin(player.angle)}const speed=dash>0?650:220;player.x=Math.max(48,Math.min(852,player.x+dx*speed*dt));player.y=Math.max(58,Math.min(548,player.y+dy*speed*dt));
 if(actionDown!==null){const charge=Math.min(1,(time-actionDown)/.65);$('charge').value=charge;$('charge-label').textContent=charge===1?'Charged — release to strike':'Gathering energy…'}if(pending!==null&&time>=pending){pending=null;attack('swing')}
 if(time>=nextPulse){pulses.push({r:15,hit:false});nextPulse=time+5}for(const p of pulses){p.r+=95*dt;if(!p.hit&&Math.abs(distance(player,{x:450,y:300})-p.r)<23){p.hit=true;if(dash<=0){contacts++;say('Pulse contact. Try dodging through the next ring.');update()}}}pulses=pulses.filter(p=>p.r<650);
 for(const s of shots){s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;for(const t of targets)if(!t.done&&distance(s,t)<30){hit(t,'projectile');s.life=0;break}}shots=shots.filter(s=>s.life>0);for(const e of effects)e.life-=dt;effects=effects.filter(e=>e.life>0);$('dodge').disabled=!running||dashReady>0;$('dodge').querySelector('small').textContent=dashReady>0?'Recovering…':'Shift';}
function circle(x,y,r,fill,stroke){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.stroke()}}
function draw(){const w=900,h=600;ctx.clearRect(0,0,w,h);const bg=ctx.createRadialGradient(450,280,10,450,300,620);bg.addColorStop(0,'#263b3d');bg.addColorStop(1,'#0d1b24');ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);ctx.lineWidth=1;
 // Architectural geometry: an open court rather than a simulated final game environment.
 ctx.strokeStyle='#66807924';for(let y=55;y<560;y+=55){ctx.beginPath();ctx.moveTo(40,y);ctx.lineTo(860,y);ctx.stroke()}for(let x=40;x<900;x+=55){ctx.beginPath();ctx.moveTo(x,45);ctx.lineTo(x,555);ctx.stroke()}
 ctx.strokeStyle='#b3ae763c';ctx.strokeRect(40,45,820,510);ctx.strokeRect(48,53,804,494);circle(450,300,210,null,'#b3ae762a');circle(450,300,145,null,'#b3ae7622');ctx.save();ctx.translate(450,300);ctx.rotate(Math.PI/4);ctx.strokeRect(-100,-100,200,200);ctx.restore();
 for(const [x,y] of [[70,75],[830,75],[70,525],[830,525]]){ctx.fillStyle='#0b171dbb';ctx.fillRect(x-20,y-10,48,38);ctx.fillStyle='#34494a';ctx.fillRect(x-17,y-25,34,36);ctx.strokeStyle='#82938966';ctx.strokeRect(x-17,y-25,34,36);circle(x,y-8,5,'#d9bc79');}
 const n=nearest();if(n&&running){ctx.setLineDash([3,8]);ctx.strokeStyle='#dac88b30';ctx.beginPath();ctx.moveTo(player.x,player.y);ctx.lineTo(n.x,n.y);ctx.stroke();ctx.setLineDash([])}
 circle(450,300,17,'#17292e','#bda77080');ctx.fillStyle='#d7bf8c';ctx.font='20px serif';ctx.textAlign='center';ctx.fillText('✧',450,307);
 for(const p of pulses){ctx.lineWidth=2;circle(450,300,p.r,null,p.hit?'#779b8740':'#e0b57990');ctx.lineWidth=1}
 for(const t of targets){const col=t.done?'#90cfb6':t.type==='charge'?'#dfbc79':t.type==='projectile'?'#91bbd9':'#d4b5ae';circle(t.x,t.y,35,'#10252b',col);circle(t.x,t.y,27,t.done?'#26483f':'#22383e',col+'88');ctx.save();ctx.translate(t.x,t.y);if(t.type==='charge')ctx.rotate(Math.PI/4);ctx.strokeStyle=col;ctx.lineWidth=2;ctx.strokeRect(-10,-10,20,20);ctx.restore();ctx.font=(canvas.clientWidth<600?'20px':'12px')+' "DM Mono",monospace';ctx.fillStyle=col;ctx.fillText(t.done?'RESTORED':t.title,t.x,t.y-48);ctx.font='10px "DM Mono",monospace';ctx.fillStyle='#a9bab4';if(canvas.clientWidth>=600)ctx.fillText(t.done?'Harmony returns':t.type==='projectile'?'Double-tap from a distance':'Move close to strike',t.x,t.y+57)}
 for(const s of shots){circle(s.x,s.y,7,'#c2e9e8');circle(s.x,s.y,12,null,'#91d8d966')}
 for(const e of effects){ctx.save();const a=e.life/e.max;ctx.globalAlpha=a;ctx.lineWidth=3;ctx.strokeStyle=e.kind==='reject'?'#ce8c83':'#e9cd91';if(e.kind==='swing'){ctx.beginPath();ctx.arc(e.x,e.y,90,e.angle-.9,e.angle+.9);ctx.stroke()}else if(e.kind==='charge'){circle(e.x,e.y,145*(1-a*.5),null,'#efcf83')}else if(!reduced){circle(e.x,e.y,25+(1-a)*50,null,e.kind==='restore'?'#9cdfba':'#9abecb')}ctx.restore()}
 // A red cloak and light blade echo Kassandra's key-art silhouette.
 ctx.save();ctx.translate(player.x,player.y);ctx.rotate(player.angle+Math.PI/2);circle(0,10,19,'#0004');ctx.fillStyle=dash>0?'#b7d9d1':'#a5454c';ctx.beginPath();ctx.moveTo(0,-12);ctx.lineTo(-16,19);ctx.quadraticCurveTo(0,11,16,19);ctx.closePath();ctx.fill();circle(0,-8,8,'#e1c8a9');ctx.strokeStyle='#f0ddaa';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(13,3);ctx.lineTo(13,-24);ctx.stroke();ctx.restore();if(actionDown!==null)circle(player.x,player.y,26,null,'#e9c983');
 ctx.fillStyle='#92a8a080';ctx.font='10px "DM Mono",monospace';ctx.textAlign='left';ctx.fillText('RESONANCE COURT / INPUT STUDY 01',62,580);ctx.textAlign='right';ctx.fillText('KASSANDRA · TRAINING MARKER',838,580);
}
function frame(ms){const dt=Math.min(.033,(ms-last)/1000||0);last=ms;if(running)step(dt);draw();requestAnimationFrame(frame)}
const mapping={KeyW:'up',ArrowUp:'up',KeyS:'down',ArrowDown:'down',KeyA:'left',ArrowLeft:'left',KeyD:'right',ArrowRight:'right'};
document.addEventListener('keydown',e=>{if(e.code==='Escape'){if(running)pause();return}if(!running||e.target.closest('a,#pause,#restart,#start,summary'))return;if(mapping[e.code]){e.preventDefault();keys.add(mapping[e.code])}if(e.code==='Space'||(e.code==='Enter'&&e.target.id==='attack')){e.preventDefault();if(!e.repeat)begin()}if(e.code==='ShiftLeft'||e.code==='ShiftRight'){e.preventDefault();if(!e.repeat)dodge()}});
document.addEventListener('keyup',e=>{if(mapping[e.code])keys.delete(mapping[e.code]);if((e.code==='Space'||(e.code==='Enter'&&e.target.id==='attack'))&&running){e.preventDefault();end()}});
for(const b of document.querySelectorAll('[data-move]')){b.onpointerdown=e=>{if(!running)return;e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.move);b.classList.add('held')};const release=()=>{keys.delete(b.dataset.move);b.classList.remove('held')};b.onpointerup=release;b.onpointercancel=release;b.onlostpointercapture=release;}
$('attack').onpointerdown=e=>{if(!running||actionPointer!==null)return;e.preventDefault();actionPointer=e.pointerId;e.currentTarget.setPointerCapture(e.pointerId);e.currentTarget.classList.add('held');begin()};$('attack').onpointerup=e=>{if(e.pointerId!==actionPointer)return;actionPointer=null;e.currentTarget.classList.remove('held');end()};$('attack').onpointercancel=()=>{actionPointer=null;actionDown=null;pending=null;second=false;$('attack').classList.remove('held');$('charge').value=0};
$('dodge').onclick=dodge;$('start').onclick=start;$('pause').onclick=()=>paused?start():pause();$('restart').onclick=()=>{reset();paused=false;start()};window.addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});
reset();enableControls(false);requestAnimationFrame(frame);
