if(!matchMedia("(prefers-reduced-motion: reduce)").matches){const style=document.createElement("style");style.textContent="@view-transition{navigation:auto}";document.head.append(style);}
document.documentElement.classList.add("js");
const plates={pink:{src:'../images/waves-01.webp',alt:'Waves poster: pink headline, curved pattern and diagonal pink form',caption:'Pink connects the headline, waves and foreground.'},blue:{src:'../images/waves-02.webp',alt:'Waves poster: pale blue headline, white wave lines and diagonal blue form',caption:'Pale blue and white give the same composition a cooler tone.'}};
document.querySelectorAll('[data-plate]').forEach(button=>button.addEventListener('click',()=>{const plate=plates[button.dataset.plate];const image=document.getElementById('colour-image');image.src=plate.src;image.alt=plate.alt;document.getElementById('colour-caption').textContent=plate.caption;document.querySelectorAll('[data-plate]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));}));
const status=document.getElementById('connection');function connection(){status.textContent=navigator.onLine?'':'You’re offline. Pocket stories remain here; full-site links need a connection.';}addEventListener('online',connection);addEventListener('offline',connection);connection();
let installPrompt;const install=document.getElementById('install');addEventListener('beforeinstallprompt',event=>{if(!install)return;event.preventDefault();installPrompt=event;install.hidden=false;});install?.addEventListener('click',async()=>{if(!installPrompt)return;try{await installPrompt.prompt();await installPrompt.userChoice;}finally{installPrompt=null;install.hidden=true;}});addEventListener('appinstalled',()=>{if(install)install.hidden=true;});
const offline=document.getElementById('offline-ready');if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js',{scope:'./'}).then(()=>navigator.serviceWorker.ready).then(()=>{if(offline)offline.textContent='This pocket edition is ready for offline reading on this device.';}).catch(()=>{if(offline)offline.textContent='Offline saving is unavailable right now. You can still read while connected.';});}else if(offline)offline.textContent='This browser does not support saving the pocket edition offline.';



const sharePocket=document.getElementById('share-pocket');if(sharePocket){sharePocket.hidden=false;sharePocket.addEventListener('click',async()=>{const url='https://www.hellojackmao.com/companion/';const status=document.getElementById('share-status');status.textContent='';document.getElementById('share-fallback').hidden=true;if(navigator.share){try{await navigator.share({title:'Jack Mao — Pocket Edition',text:'A little closer to the work.',url});return;}catch(error){if(error.name==='AbortError')return;}}try{await navigator.clipboard.writeText(url);status.textContent='Pocket link copied. Ready to share.';}catch{status.textContent='Select and copy the address below.';document.getElementById('share-fallback').hidden=false;}});}
