'use strict';
(() => {
 const $=id=>document.getElementById(id), key='tend.web-prototype.v1';
 const defaults=()=>({version:1,habits:[{id:'stretch',name:'Morning stretch'},{id:'water',name:'Drink water'},{id:'read',name:'Read 10 pages'},{id:'outside',name:'Step outside'}],days:{}});
 const dateKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
 const fromKey=k=>{const [y,m,d]=k.split('-').map(Number);return new Date(y,m-1,d,12)};
 const today=()=>dateKey(new Date());
 let state=defaults(),selected=today(),month=fromKey(selected),view='home',storage=true;
 try {const raw=localStorage.getItem(key);if(raw){const s=JSON.parse(raw);if(s.version!==1||!Array.isArray(s.habits)||!s.habits.length||s.habits.length>12||!s.days||typeof s.days!=='object'||Array.isArray(s.days))throw Error('Invalid state');const ids=new Set();for(const h of s.habits){if(typeof h.id!=='string'||typeof h.name!=='string'||!h.name.trim()||h.name.length>60||ids.has(h.id))throw Error('Invalid habit');ids.add(h.id)}for(const [k,d] of Object.entries(s.days)){if(!/^\d{4}-\d{2}-\d{2}$/.test(k)||!d||!Array.isArray(d.done)||!d.done.every(id=>ids.has(id))||typeof d.note!=='string'||d.note.length>400)throw Error('Invalid day')}state=s}}catch{storage=false;$('storage-warning').hidden=false}
 function save(){try{localStorage.setItem(key,JSON.stringify(state));storage=true;$('storage-warning').hidden=true}catch{storage=false;$('storage-warning').hidden=false}return storage}
 function day(k=selected){return state.days[k]||{done:[],note:''}}
 function writable(){return state.days[selected]||(state.days[selected]={done:[],note:''})}
 function announce(text){$('announcement').textContent=text}
 function button(text,fn){const b=document.createElement('button');b.type='button';b.textContent=text;b.addEventListener('click',fn);return b}
 function select(k){selected=k;month=fromKey(k);render()}
 function render(){const d=fromKey(selected),entry=day(),done=new Set(entry.done).size,total=state.habits.length,pct=Math.round(done/total*100);
 $('view-label').textContent={home:'Your daily rhythm',calendar:'The bigger picture',journal:'Make room to reflect'}[view];
 $('view-title').textContent=view==='home'?d.toLocaleDateString('en',{weekday:'long'}):view==='calendar'?'Calendar':selected===today()?'Today':'Your reflection';
 $('date-label').textContent=d.toLocaleDateString('en',{month:'long',day:'numeric',year:'numeric'});
 $('progress-heading').textContent=`${done} of ${total} complete`;$('percent').textContent=pct+'%';$('ring').style.setProperty('--progress',pct+'%');$('ring').setAttribute('aria-valuenow',pct);
 $('encouragement').textContent=done===total?'A little care, carried through.':done?'A small step is still a step.':'Start wherever feels right.';$('habit-count').textContent=total+' daily habits';
 $('week').replaceChildren();const start=fromKey(selected);start.setDate(start.getDate()-((start.getDay()+6)%7));for(let i=0;i<7;i++){const date=new Date(start);date.setDate(start.getDate()+i);const k=dateKey(date),b=button('',()=>select(k)),name=document.createElement('span');name.textContent=date.toLocaleDateString('en',{weekday:'short'});b.append(name,String(date.getDate()));b.setAttribute('aria-label',date.toLocaleDateString('en',{weekday:'long',month:'long',day:'numeric'}));b.setAttribute('aria-pressed',k===selected);$('week').append(b)}
 $('habits').replaceChildren();for(const h of state.habits){const completed=entry.done.includes(h.id),b=button('',()=>{const e=writable();e.done=e.done.includes(h.id)?e.done.filter(id=>id!==h.id):[...e.done,h.id];save();render();[...$('habits').children].find(b=>b.dataset.habit===h.id)?.focus({preventScroll:true});announce(h.name+(e.done.includes(h.id)?' completed.':' unchecked.'))});b.className='habit';b.dataset.habit=h.id;b.setAttribute('aria-pressed',completed);const check=document.createElement('span');check.className='check';check.setAttribute('aria-hidden','true');check.textContent='✓';const name=document.createElement('span');name.className='habit-name';name.textContent=h.name;const sub=document.createElement('small');sub.textContent=completed?'A little care, done.':'A moment for you';name.append(sub);b.append(check,name);$('habits').append(b)}
 $('add-open').disabled=total>=12;$('add-open').querySelector('span').textContent=total>=12?'12 habits — room to focus':'Add a small habit';
 renderCalendar();$('journal').value=entry.note;$('char-count').textContent=entry.note.length+' / 400';$('save-state').textContent=entry.note?(storage?'Saved in this browser':'Kept for this visit'):'Your words stay here.';
 }
 function renderCalendar(){const y=month.getFullYear(),m=month.getMonth();$('month-title').textContent=month.toLocaleDateString('en',{month:'long',year:'numeric'});$('calendar').replaceChildren();const offset=(new Date(y,m,1).getDay()+6)%7;for(let i=0;i<offset;i++)$('calendar').append(document.createElement('span'));for(let n=1;n<=new Date(y,m+1,0).getDate();n++){const d=new Date(y,m,n,12),k=dateKey(d),e=day(k),b=button(n,()=>select(k));b.setAttribute('aria-pressed',k===selected);b.setAttribute('aria-label',d.toLocaleDateString('en',{month:'long',day:'numeric',year:'numeric'})+`, ${e.done.length} habits complete`+(e.note?', reflection saved':''));if(k===today())b.classList.add('is-today');if(e.done.length||e.note)b.classList.add('has-entry');$('calendar').append(b)}
 $('summary-date').textContent=fromKey(selected).toLocaleDateString('en',{month:'long',day:'numeric'});$('summary-count').textContent=`${new Set(day().done).size} of ${state.habits.length} habits complete`;$('summary-note').textContent=day().note||'No reflection yet. There’s room for a few words.';
 }
 function navigate(next){view=next;for(const name of ['home','calendar','journal'])$(name+'-panel').hidden=name!==view;document.querySelectorAll('[data-view]').forEach(b=>{if(b.dataset.view===view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});month=fromKey(selected);render();$('view-title').tabIndex=-1;$('view-title').focus({preventScroll:true});if(matchMedia('(max-width:760px)').matches)$('app').scrollIntoView({behavior:'instant',block:'start'})}
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>navigate(b.dataset.view));$('today').onclick=()=>select(today());$('reflect').onclick=()=>navigate('journal');$('open-day').onclick=()=>navigate('home');
 $('prev-month').onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()-1,1,12);renderCalendar()};$('next-month').onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()+1,1,12);renderCalendar()};
 $('journal').addEventListener('input',()=>{writable().note=$('journal').value;save();$('char-count').textContent=$('journal').value.length+' / 400';$('save-state').textContent=storage?'Saved in this browser':'Kept for this visit'});
 document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{const t=$('journal'),prefix=t.value.trim()?t.value+'\n\n':'';t.value=(prefix+b.dataset.prompt).slice(0,400);t.dispatchEvent(new Event('input'));t.focus();t.setSelectionRange(t.value.length,t.value.length)});
 $('add-open').onclick=()=>{$('add-form').reset();$('add-error').textContent='';$('add-dialog').showModal()};
 $('add-form').onsubmit=e=>{e.preventDefault();const name=$('habit-name').value.trim();if(!name){$('add-error').textContent='Give your habit a short name.';return}if(state.habits.some(h=>h.name.toLowerCase()===name.toLowerCase())){$('add-error').textContent='That habit is already here.';return}if(state.habits.length>=12)return;state.habits.push({id:'habit-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7),name});save();$('add-dialog').close();render();announce('Habit added: '+name)};
 document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());$('reset-open').onclick=()=>$('reset-dialog').showModal();$('reset-confirm').onclick=()=>{state=defaults();selected=today();month=fromKey(selected);save();$('reset-dialog').close();navigate('home');announce('Prototype reset. Four demo habits restored.')};
 render();
})();
